<div class="row" data-equalizer="donate">
    <div class="{% if user %}large-12{% else %}large-12{% endif %} medium-4 xlarge-12 small-12 columns text-center" data-equalizer-watch="donate">
        <form action="https://www.paypal.com/cgi-bin/webscr" class="vertical-centered" method="post" target="_top" style="text-align: center; margin: 10px auto 10px;">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHVwYJKoZIhvcNAQcEoIIHSDCCB0QCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYATwHAMk9X/M9LBEFwmRHT0rrH2EPTn/LrbNEDXnT8hnDQG19d1aw+2VpGQoWpBZ2NG5G69swslh89AZzye0CKjEEzezmD4aN1OumNakbzTlNB4Zqe8vA5iO+28KxZsyVwgXeXbI46mKArxRcWgR0SQVwt2/AZFteK1DT9r4VN6WjELMAkGBSsOAwIaBQAwgdQGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIH8+IqdfZoAqAgbB5ShRRLdPKS01Y1hSUS+aJZp3WXbOhZw6AKFre9YWNpBtKYkfHiTqT3DD+edYGtRzmA4EV/lFnMazciOgyHvLsLit6XRGjaZ2D/oQXjfZjgYUlSUKG4t68kWrbSgo9CMJYsetcaDt4DiyogmjzcYqEq762KHbHeZsL9Sn6Kf+3iiRauEvC0bWuex4XOVka8Kfpymoc4bbdixN0rbP6mTMSpQ++yCrU91cI2KXmzA4v4aCCA4cwggODMIIC7KADAgECAgEAMA0GCSqGSIb3DQEBBQUAMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTAeFw0wNDAyMTMxMDEzMTVaFw0zNTAyMTMxMDEzMTVaMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwUdO3fxEzEtcnI7ZKZL412XvZPugoni7i7D7prCe0AtaHTc97CYgm7NsAtJyxNLixmhLV8pyIEaiHXWAh8fPKW+R017+EmXrr9EaquPmsVvTywAAE1PMNOKqo2kl4Gxiz9zZqIajOm1fZGWcGS0f5JQ2kBqNbvbg2/Za+GJ/qwUCAwEAAaOB7jCB6zAdBgNVHQ4EFgQUlp98u8ZvF71ZP1LXChvsENZklGswgbsGA1UdIwSBszCBsIAUlp98u8ZvF71ZP1LXChvsENZklGuhgZSkgZEwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAgV86VpqAWuXvX6Oro4qJ1tYVIT5DgWpE692Ag422H7yRIr/9j/iKG4Thia/Oflx4TdL+IFJBAyPK9v6zZNZtBgPBynXb048hsP16l2vi0k5Q2JKiPDsEfBhGI+HnxLXEaUWAcVfCsQFvd2A1sxRr67ip5y2wwBelUecP3AjJ+YcxggGaMIIBlgIBATCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE1MDgyNzA3MjMzNlowIwYJKoZIhvcNAQkEMRYEFMXRReKjYt8fD0ckzZ4PYtoA+tp+MA0GCSqGSIb3DQEBAQUABIGAZ7qOLr3oukZik/l6NU4GXpCyBSOPbtkcXpYPGAHxs/cgOn+4HlvrJfI/VKvfPcqwTsd55+rhgdM2EtFLzyjgfrYJFYlwpZ2gYx1wU3b0D5/uAdaS5NC+EdoBe5NLYsiruG8FguQGlqw628q7oYoZm820kbpeXeyouNdQ5wo2ZyA=-----END PKCS7-----
        ">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
    
    <div class="{% if user %}large-12{% else %}large-12{% endif %} xlarge-12 small-12 columns" data-equalizer-watch="donate">
        Please consider making a donation of $10 or more (or less) via PayPal to support further development of <em>{{ site_name }}</em>!
        Every dollar helps free up time for development or obtain resources as well as provide motivation!
    </div>
</div>